### ISSUE TITLE
Bitte: MiniBeispiel für die Art der Anwendung

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/content#1]
Wie nutzt Du dieses AddOn??

**Comment by eaCe** [comment]
Ich schreibe die Tage mal etwas dazu. Generell ist es für Testumgebungen gedacht um ohne SQL-Dumps zu arbeiten. Man könnte auch Demos damit erstellen.

**Comment by AWqxKAWERbXo** [comment]
https://github.com/FriendsOfREDAXO/content/blob/main/README.md ist befüllt. Close?
