### ISSUE TITLE
Umbenennen :|

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/content#2]

**Comment by AWqxKAWERbXo** [comment]
In content? Mithilfe benötigt? Muss sowas nicht in den core? ;)

**Comment by eaCe** [comment]
Der Prefix muss raus und content wäre vermutlich zu allgemein. Ich suche noch nach Namen :)

**Comment by AWqxKAWERbXo** [comment]
`structure_helper`, `content`

**Comment by aeberhard** [comment]
`content_helper` `content_tool` `content_toolbox`

**Comment by AWqxKAWERbXo** [comment]
Wenn sich der Klassenname daraus ableitet, bin ich für was kurzes.

**Comment by eaCe** [comment]
cntnt

**Comment by AWqxKAWERbXo** [comment]
`c`

**Comment by eaCe** [comment]
Dann eben doch nur content.
